[package]
name = "cryptopals"
version = "0.1.0"
authors = ["yepchris"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
hex = "0.3.2"
log = {version = "^0.4.6", features = ["max_level_debug", "release_max_level_warn"] }
rust-crypto = "^0.2"
rand = "0.6.5"
simplelog = "^0.5.3"